[package]
name = "exoskeleton"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = { version = "0.7.0", features = [ "im", "svg"]}
rand = "0.8.4"
lazy_static = "1.4.0"
dirs = "3.0.2"
